modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/jshipley/SpiritAPI/issues"
license = "MIT"

[[mods]]
modId = "spiritapi"
version = "${version}"
displayName = "SpiritAPI"
authors = "jship"
description = '''
A cross-platform architectury-based transport API for my mods.
'''
logoFile = "assets/spiritapi/spiritapi.png"

[[dependencies.spiritapi]]
modId = "neoforge"
type = "required"
versionRange = "[21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spiritapi]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spiritapi]]
modId = "architectury"
type = "required"
versionRange = "[16.0,)"
ordering = "AFTER"
side = "BOTH"
